
compatibility_date = "2022-05-03"
main = "index.ts"
logpush = true
compatibility_flags = [ "nodejs_compat" ]

[env.dev]
name = "solana-foundation-bot-dev"

[env.staging]
name = "solana-foundation-bot-staging"

[env.prod]
name = "solana-foundation-bot-prod"

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["UserDO"]

# 1632540473

[env.dev.vars]
# do not change this string EVER post launch
ENVIRONMENT = "dev"
CLOUDFLARE_ACCOUNT_ID = "kp1197"
TELEGRAM_BOT_INSTANCE_DISPLAY_NAME = "DEV"
ADMIN_TELEGRAM_USER_IDS = "6434185018"
SUPER_ADMIN_USER_ID = "6434185018"
TELEGRAM_BOT_DISPLAY_NAME = "Solana Foundation on Telegram"
TELEGRAM_BOT_TAGLINE = "A Tagline."
TELEGRAM_BOT_SERVER_URL = "https://api.telegram.org"
TELEGRAM_BOT_ID = "...TODO..."
TELEGRAM_BOT_USERNAME = "solana-foundation-bot-dev"
DOWN_FOR_MAINTENANCE = "false"
QUESTION_TIMEOUT_MS = "30000"

[env.staging.vars]
# do not change this string EVER post launch
ENVIRONMENT = "staging"
CLOUDFLARE_ACCOUNT_ID = "kp1197"
TELEGRAM_BOT_INSTANCE_DISPLAY_NAME = "STAGING"
ADMIN_TELEGRAM_USER_IDS = "6434185018"
SUPER_ADMIN_USER_ID = "6434185018"
TELEGRAM_BOT_DISPLAY_NAME = "Solana Foundation on Telegram"
TELEGRAM_BOT_TAGLINE = "A Tagline."
TELEGRAM_BOT_SERVER_URL = "https://api.telegram.org"
TELEGRAM_BOT_ID = "...TODO..."
TELEGRAM_BOT_USERNAME = "solana-foundation-bot-staging"
DOWN_FOR_MAINTENANCE = "false"
QUESTION_TIMEOUT_MS = "30000"

[env.prod.vars]
# do not change this string EVER post launch
ENVIRONMENT = "prod"
CLOUDFLARE_ACCOUNT_ID = "kp1197"
TELEGRAM_BOT_INSTANCE_DISPLAY_NAME = "PROD"
ADMIN_TELEGRAM_USER_IDS = "6434185018"
SUPER_ADMIN_USER_ID = "6434185018"
TELEGRAM_BOT_DISPLAY_NAME = "Solana Foundation on Telegram"
TELEGRAM_BOT_TAGLINE = "A Tagline."
TELEGRAM_BOT_SERVER_URL = "https://api.telegram.org"
TELEGRAM_BOT_ID = "...TODO..."
TELEGRAM_BOT_USERNAME = "solana-foundation-bot-prod"
DOWN_FOR_MAINTENANCE = "false"
QUESTION_TIMEOUT_MS = "30000"

[env.dev.durable_objects]
bindings = [
    {name = "UserDO", class_name = "UserDO" }
]

[env.beta.durable_objects]
bindings = [
    {name = "UserDO", class_name = "UserDO" }
]

[env.sim.durable_objects]
bindings = [
    {name = "UserDO", class_name = "UserDO" }
]

# The 'wake up!' cron trigger - keeps the price tracker tracking the prices.
# If you update the patterns, update the index.js because it filters based on pattern.
[triggers]
crons = [ "* * * * *", "*/30 * * * *" ]
